# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QiY9SkLCKkJlvUom5r3PjuwWC3VoUaP1
"""

import json
import os
import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import plotly.graph_objects as go

# Konfigurasi Halaman Streamlit
st.set_page_config(
    page_title="AI Stock Analysis & Recommendation Dashboard",
    page_icon="📈",
    layout="wide"
)

# Fungsi untuk memuat referensi buku dari direktori lokal / GitHub
@st.cache_data
def load_book_references():
    path = "books_reference/bulkowski_patterns.json"
    if os.path.exists(path):
        with open(path, "r") as f:
            return json.load(f)
    return {"reference_books": [], "patterns_rules": {}}

book_data = load_book_references()

# Sidebar Navigasi & Input Parameter
st.sidebar.header("⚙️ Konfigurasi Analisis")
ticker_symbol = st.sidebar.text_input("Kode Saham (Yahoo Finance format)", value="BBCA.JK")
period_option = st.sidebar.selectbox("Rentang Waktu", ["3mo", "6mo", "1y", "2y"], index=2)
interval_option = st.sidebar.selectbox("Interval", ["1d", "1wk"], index=0)

st.sidebar.markdown("---")
st.sidebar.subheader("📚 Sumber Dasar Literatur")
st.sidebar.info(
    "Dasbor ini mengintegrasikan kaidah analisis dari buku-buku standar industri seperti "
    "*Visual Guide to Chart Patterns* (Thomas N. Bulkowski)[cite: 6], *The Intelligent Investor* (Benjamin Graham), "
    "dan *Trading in the Zone* (Mark Douglas)."
)

st.title("📊 Dasbor Analisis & Rekomendasi Saham Presisi")
st.markdown(
    f"Analisis komprehensif berbasis data historis dan kaidah literatur keuangan klasik untuk **{ticker_symbol.upper()}**."
)

@st.cache_data
def fetch_stock_data(ticker, period, interval):
    try:
        df = yf.download(ticker, period=period, interval=interval, progress=False)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.droplevel(1)
        return df
    except Exception as e:
        st.error(f"Gagal mengambil data: {e}")
        return pd.DataFrame()

data = fetch_stock_data(ticker_symbol, period_option, interval_option)

if data.empty:
    st.warning("Tidak ada data ditemukan untuk ticker tersebut. Periksa kembali simbol saham (contoh: BBCA.JK, AAPL, TLKM.JK).")
else:
    # Perhitungan Indikator Teknikal
    data['MA20'] = data['Close'].rolling(window=20).mean()
    data['MA50'] = data['Close'].rolling(window=50).mean()

    # RSI Calculation
    delta = data['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    data['RSI'] = 100 - (100 / (1 + rs))

    # Harga Terakhir & Metrik
    latest_close = float(data['Close'].iloc[-1])
    prev_close = float(data['Close'].iloc[-2])
    price_change = latest_close - prev_close
    pct_change = (price_change / prev_close) * 100
    latest_rsi = float(data['RSI'].iloc[-1])
    latest_ma20 = float(data['MA20'].iloc[-1])
    latest_ma50 = float(data['MA50'].iloc[-1])

    # Metrik Utama
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Harga Terakhir", f"{latest_close:,.2f}", f"{pct_change:+.2f}%")
    col2.metric("RSI (14)", f"{latest_rsi:.2f}")
    col3.metric("MA 20", f"{latest_ma20:,.2f}")
    col4.metric("MA 50", f"{latest_ma50:,.2f}")

    # Visualisasi Grafik Candlestick & Indikator
    st.subheader("📉 Grafik Harga & Analisis Teknikal (Candlestick)")
    fig = go.Figure()
    fig.add_trace(go.Candlestick(
        x=data.index,
        open=data['Open'],
        high=data['High'],
        low=data['Low'],
        close=data['Close'],
        name='Candlestick'
    ))
    fig.add_trace(go.Scatter(x=data.index, y=data['MA20'], line=dict(color='orange', width=1.5), name='MA 20'))
    fig.add_trace(go.Scatter(x=data.index, y=data['MA50'], line=dict(color='blue', width=1.5), name='MA 50'))

    fig.update_layout(
        title=f'Pergerakan Harga Saham {ticker_symbol.upper()}',
        yaxis_title='Harga',
        xaxis_title='Tanggal',
        template='plotly_dark',
        height=500
    )
    st.plotly_chart(fig, use_container_width=True)

    # Modul Rekomendasi Berbasis Literatur & Validasi Presisi
    st.subheader("💡 Rekomendasi & Validasi Berbasis Literatur Buku")

    col_rec1, col_rec2 = st.columns([2, 1])

    with col_rec1:
        st.markdown("### Evaluasi Sinyal & Kaidah Analisis")

        signals = []
        recommendation = "HOLD / WAIT & SEE"
        rec_color = "orange"

        if latest_close > latest_ma20 and latest_ma20 > latest_ma50:
            signals.append("✔ **Tren Utama Bullish**: Harga berada di atas MA20 dan MA50 (Konfirmasi tren naik lanjutan).")
        elif latest_close < latest_ma20 and latest_ma20 < latest_ma50:
            signals.append("✖ **Tren Utama Bearish**: Harga berada di bawah indikator tren utama.")

        if latest_rsi < 30:
            signals.append("✔ **Kondisi Oversold (RSI < 30)**: Potensi pembalikan arah naik (*rebound*), sejalan dengan aturan pola *Double Bottom*.")
            recommendation = "STRONG BUY (Akumulasi Bertahap)"
            rec_color = "green"
        elif latest_rsi > 70:
            signals.append("✖ **Kondisi Overbought (RSI > 70)**: Risiko koreksi tinggi, sesuaikan dengan prinsip manajemen risiko Thomas Bulkowski terkait *throwback*[cite: 6].")
            recommendation = "TAKE PROFIT / SELL"
            rec_color = "red"
        else:
            signals.append("ℹ **RSI Netral (30 - 70)**: Pasar bergerak konsolidasi. Perhatikan pola volume dan area *support/resistance*.")

        for sig in signals:
            st.markdown(f"- {sig}")

        st.markdown(f"### Keputusan Rekomendasi: <span style='color:{rec_color}'>{recommendation}</span>", unsafe_allow_html=True)

    with col_rec2:
        st.markdown("### 📖 Referensi Buku Terhubung")
        if book_data.get("reference_books"):
            for book in book_data["reference_books"][:2]:
                st.markdown(f"**{book['title']}** ({book['year']}) — *{book['author']}*")
                for rule in book['core_principles'][:1]:
                    st.caption(f"• {rule}")
                st.markdown("---")

    # Bagian Transparansi Data & Sumber Literatur Lengkap
    with st.expander("🔍 Lihat Detail Literatur Pendukung & Aturan Validasi"):
        st.json(book_data)